apiVersion: v1
kind: Service
metadata:
  name: devcalc-service
  namespace: tp2
spec:
  selector:
    app: devcalc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30003
      protocol: TCP
  type: NodePort

