apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tp2
spec:
  selector:
    app: nginx-busybox
  ports:
    - name: http
      port: 8081
      targetPort: 80
      protocol: TCP
  type: ClusterIP
