name: env-demo.yml
on:
  push:
jobs:
  env-demo:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: "staging"
    steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Display Environment Variable
          run: echo $DEPLOY_ENV
