name: secret-demo.yml
on:
  push:
    branches:
      - main
jobs:
    secret-demo:
        runs-on: ubuntu-latest
        steps:
        - name: Echo API_KEY
          env:
            API_KEY: ${{ secrets.API_KEY }}
          run: echo "API_KEY configurada"